services:
  db:
    container_name: ${MYSQL_HOST}
    image: mysql
    restart: always
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-net

  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
    networks:
      - app-net

  server:
    container_name: server_container
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9000:9000
    networks:
      - app-net

volumes:
  mysql:

networks:
  app-net:
